main:
  - name: 청주충북환경연합
    url: http://cjcb.ekfem.or.kr/%EC%B2%AD%EC%A3%BC%EC%B6%A9%EB%B6%81%ED%99%98%EA%B2%BD%EC%97%B0%ED%95%A9/%EC%B2%AD%EC%A3%BC%EC%B6%A9%EB%B6%81%ED%99%98%EA%B2%BD%EC%97%B0%ED%95%A9%EC%9D%80/
    weight: 1
  - name:  청주충북환경연합은?
    url: http://cjcb.ekfem.or.kr/%ec%b2%ad%ec%a3%bc%ec%b6%a9%eb%b6%81%ed%99%98%ea%b2%bd%ec%97%b0%ed%95%a9/%ec%b2%ad%ec%a3%bc%ec%b6%a9%eb%b6%81%ed%99%98%ea%b2%bd%ec%97%b0%ed%95%a9%ec%9d%80/
    weight: 1
    parent: 청주충북환경연합
  - name: 걸어온길
    url: http://cjcb.ekfem.or.kr/%ec%b2%ad%ec%a3%bc%ec%b6%a9%eb%b6%81%ed%99%98%ea%b2%bd%ec%97%b0%ed%95%a9/%ea%b1%b8%ec%96%b4%ec%98%a8%ea%b8%b8/
    weight: 2
    parent: 청주충북환경연합
  - name: 조직운영
    url: http://cjcb.ekfem.or.kr/%ec%b2%ad%ec%a3%bc%ec%b6%a9%eb%b6%81%ed%99%98%ea%b2%bd%ec%97%b0%ed%95%a9/%ec%a1%b0%ec%a7%81%ec%9a%b4%ec%98%81/
    weight: 3
    parent: 청주충북환경연합
  - name: 주요활동
    url: http://cjcb.ekfem.or.kr/%ec%b2%ad%ec%a3%bc%ec%b6%a9%eb%b6%81%ed%99%98%ea%b2%bd%ec%97%b0%ed%95%a9/%ec%a3%bc%ec%9a%94%ed%99%9c%eb%8f%99/
    weight: 4
    parent: 청주충북환경연합
  - name: 찾아오시는 길
    url: http://cjcb.ekfem.or.kr/%ec%b0%be%ec%95%84%ec%98%a4%ec%8b%9c%eb%8a%94-%ea%b8%b8/
    weight: 5
    parent: 청주충북환경연합

  - name: 알림마당
    url: 
    weight: 2
  - name: 공지사항
    url: https://demo-osas-220817.campaignus.me/15?category=l48421Z385
    weight: 1
    parent: 알림마당
  - name: 활동소식
    url: https://demo-osas-220817.campaignus.me/15?category=61d5T752mK
    weight: 2
    parent: 알림마당
  - name: 초록칼럼
    url: https://demo-osas-220817.campaignus.me/15?category=26m6D24g35
    weight: 3
    parent: 알림마당
  - name: 성명서 보도자료
    url: https://demo-osas-220817.campaignus.me/15?category=uJ838hWW0b
    weight: 4
    parent: 알림마당
  - name: 주요일정
    url: http://cjcb.ekfem.or.kr/%ec%82%ac%eb%ac%b4%ec%b2%98-%ec%9d%bc%ec%a0%95/
    weight: 5
    parent: 알림마당

  - name: 자료실
    url: 
    weight: 3
  - name: 사진자료실
    url: https://demo-osas-220817.campaignus.me/16?category=28373033W1
    weight: 1
    parent: 자료실
  - name: 환경자료실
    url: https://demo-osas-220817.campaignus.me/16?category=D1H7422T4b
    weight: 2
    parent: 자료실
  - name: 동영상 자료실
    url: https://demo-osas-220817.campaignus.me/16?category=14u3F63M5Q
    weight: 3
    parent: 자료실
  - name: 회원소식지
    url: https://demo-osas-220817.campaignus.me/16?category=66HS62B024
    weight: 4
    parent: 자료실

  - name: 회원마당
    url: 
    weight: 4
  - name: 회원이야기
    url: https://demo-osas-220817.campaignus.me/17?category=aK0u540481
    weight: 1
    parent: 회원마당
  - name: 소모임방
    url: https://demo-osas-220817.campaignus.me/17?category=O11678G4CP
    weight: 2
    parent: 회원마당

  - name: 풀꿈자연학교
    url: https://demo-osas-220817.campaignus.me/19?category=837ww22n33
    weight: 5

  - name: 후원하기
    url: http://cjcb.ekfem.or.kr/%ED%9B%84%EC%9B%90%ED%95%98%EA%B8%B0/
    weight: 6
  - name: 후원하기
    url: http://cjcb.ekfem.or.kr/%ed%9b%84%ec%9b%90%ed%95%98%ea%b8%b0/
    weight: 1
    parent: 후원하기
  - name: 회원가입
    url: https://online.mrm.or.kr/BLPNJpi
    weight: 2
    parent: 후원하기
  - name: 해피빈
    url: http://happylog.naver.com/cjcbkfem.do
    weight: 3
    parent: 후원하기
  - name: 자원활동 신청
    url: http://cjcb.ekfem.or.kr/%ed%9b%84%ec%9b%90%ed%95%98%ea%b8%b0/%ec%9e%90%ec%9b%90%ed%99%9c%eb%8f%99-%ec%8b%a0%ec%b2%ad/
    weight: 4
    parent: 후원하기
  - name: 이용약관
    url: http://cjcb.ekfem.or.kr/category/%ec%9d%b4%ec%9a%a9%ec%95%bd%ea%b4%80/
    weight: 5
    parent: 후원하기
